version: "3"
services:
    roscore:
        container_name: roscore
        build:
            context: .
            args:
                ROS_DISTRO: ${ROS_DISTRO}
                ROS_MASTER_URI: http://${ROS_MASTER_IP}:${ROS_MASTER_PORT}
                SCRIPT_FOLDER: roscore
        networks:
            witty:
                ipv4_address: ${ROS_MASTER_IP}
        volumes:
            - workspace:/root/catkin_ws/src
        tty: true
        stdin_open: true
    roslaunch_1:
        build:
            context: .
            args:
                ROS_DISTRO: ${ROS_DISTRO}
                ROS_MASTER_URI: http://${ROS_MASTER_IP}:${ROS_MASTER_PORT}
                SCRIPT_FOLDER: roslaunch
        networks:
            witty:
                ipv4_address: ${ROSRUN_NODE_1}
        env_file:
            - .env
            - ./envs/.env_turtlebot_gazebo
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - workspace:/root/catkin_ws/src
        tty: true
        stdin_open: true
        depends_on:
            - roscore
    # rosrun_2:
    #     build:
    #         context: .
    #         args:
    #             ROS_DISTRO: ${ROS_DISTRO}
    #             ROS_MASTER_URI: http://${ROS_MASTER_IP}:${ROS_MASTER_PORT}
    #             SCRIPT_FOLDER: rosrun
    #     networks:
    #         witty:
    #             ipv4_address: ${ROSRUN_NODE_2}
    #     env_file:
    #         - .env
    #         - ./envs/.env_ex1
    #     volumes:
    #         - workspace:/root/catkin_ws/src
    #     tty: true
    #     stdin_open: true
    #     depends_on:
    #         - rosrun_1

networks:
    witty:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}

volumes:
    workspace:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${PWD}/workspace
